/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformacoesPaginaRouteImport } from './routes/informacoes.$pagina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesPaginaRoute = InformacoesPaginaRouteImport.update({
  id: '/informacoes/$pagina',
  path: '/informacoes/$pagina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/informacoes/$pagina': typeof InformacoesPaginaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/informacoes/$pagina': typeof InformacoesPaginaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/informacoes/$pagina': typeof InformacoesPaginaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/informacoes/$pagina'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/informacoes/$pagina'
  id: '__root__' | '/' | '/informacoes/$pagina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InformacoesPaginaRoute: typeof InformacoesPaginaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes/$pagina': {
      id: '/informacoes/$pagina'
      path: '/informacoes/$pagina'
      fullPath: '/informacoes/$pagina'
      preLoaderRoute: typeof InformacoesPaginaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InformacoesPaginaRoute: InformacoesPaginaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
